defmodule GovBidify.ContractAwards.ContractAward do
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:award_id_piid, :string, []}
  schema "contract_awards" do
    field :award_or_idv_flag, :string
    field :naics_code, :string
    field :receives_financial_assistance, :string
    field :joint_venture_economic_disadvantaged_women_owned_small_bus, :string
    field :inherently_governmental_functions_description, :string
    field :awarding_office_name, :string
    field :international_organization, :string
    field :award_type_code, :string
    field :us_tribal_government, :string
    field :modification_number, :string
    field :solicitation_identifier, :string
    field :native_hawaiian_organization_owned_firm, :string
    field :federal_action_obligation, :string
    field :us_local_government, :string
    field :municipality_local_government, :string
    field :alaskan_native_corporation_owned_firm, :string
    field :solicitation_procedures_code, :string
    field :labor_surplus_area_firm, :string
    field :interagency_contracting_authority, :string
    field :evaluated_preference, :string
    field :funding_agency_code, :string
    field :recipient_state_name, :string
    field :number_of_actions, :string
    field :subcontinent_asian_asian_indian_american_owned_business, :string
    field :for_profit_organization, :string
    field :recipient_country_code, :string
    field :parent_award_type, :string
    field :recipient_parent_duns, :string
    field :dod_claimant_program_description, :string
    field :school_district_local_government, :string
    field :receives_contracts_and_financial_assistance, :string
    field :recipient_name_raw, :string
    field :country_of_product_or_service_origin_code, :string
    field :extent_competed_code, :string
    field :parent_award_agency_id, :string
    field :construction_wage_rate_requirements, :string
    field :prime_award_transaction_recipient_cd_original, :string
    field :information_technology_commercial_item_category, :string
    field :"outlayed_amount_from_COVID-19_supplementals_for_overall_award", :string
    field :primary_place_of_performance_zip_4, :string
    field :action_date, :string
    field :city_local_government, :string
    field :corporate_entity_tax_exempt, :string
    field :idv_type_code, :string
    field :prime_award_transaction_place_of_performance_cd_original, :string
    field :multi_year_contract_code, :string
    field :number_of_offers_received, :string
    field :last_modified_date, :string
    field :veteran_owned_business, :string
    field :contract_transaction_unique_key, :string
    field :country_of_product_or_service_origin, :string
    field :highly_compensated_officer_3_amount, :string
    field :c8a_program_participant, :string
    field :service_disabled_veteran_owned_business, :string
    field :commercial_item_acquisition_procedures_code, :string
    field :naics_description, :string
    field :simplified_procedures_for_certain_commercial_items_code, :string
    field :prime_award_transaction_place_of_performance_cd_current, :string
    field :small_agricultural_cooperative, :string
    field :contract_bundling, :string
    field :parent_award_single_or_multiple, :string
    field :simplified_procedures_for_certain_commercial_items, :string
    field :recipient_doing_business_as_name, :string
    field :interstate_entity, :string
    field :recovered_materials_sustainability, :string
    field :period_of_performance_current_end_date, :string
    field :recipient_parent_name_raw, :string
    field :community_developed_corporation_owned_firm, :string
    field :airport_authority, :string
    field :sba_certified_8a_joint_venture, :string
    field :commercial_item_acquisition_procedures, :string
    field :treasury_accounts_funding_this_award, :string
    field :fair_opportunity_limited_sources_code, :string
    field :awarding_agency_name, :string
    field :nonprofit_organization, :string
    field :research, :string
    field :partnership_or_limited_liability_partnership, :string
    field :recipient_duns, :string
    field :sam_exception_description, :string
    field :planning_commission, :string
    field :black_american_owned_business, :string
    field :state_controlled_institution_of_higher_learning, :string
    field :historically_black_college, :string
    field :labor_standards_code, :string
    field :solicitation_procedures, :string
    field :historically_underutilized_business_zone_hubzone_firm, :string
    field :a76_fair_act_action_code, :string
    field :prime_award_transaction_recipient_cd_current, :string
    field :recipient_uei, :string
    field :major_program, :string
    field :a76_fair_act_action, :string
    field :land_grant_college, :string
    field :transaction_description, :string
    field :native_american_owned_business, :string
    field :recipient_parent_uei, :string
    field :highly_compensated_officer_2_amount, :string
    field :transaction_number, :string
    field :foreign_owned, :string
    field :local_area_set_aside_code, :string
    field :type_of_set_aside_code, :string
    field :inherently_governmental_functions, :string
    field :parent_award_single_or_multiple_code, :string
    field :cost_or_pricing_data_code, :string
    field :subchapter_scorporation, :string
    field :other_than_full_and_open_competition, :string
    field :hispanic_american_owned_business, :string
    field :ordering_period_end_date, :string
    field :"obligated_amount_from_COVID-19_supplementals_for_overall_award", :string
    field :highly_compensated_officer_3_name, :string
    field :transit_authority, :string
    field :prime_award_transaction_recipient_county_fips_code, :string
    field :highly_compensated_officer_4_name, :string
    field :dot_certified_disadvantage, :string
    field :veterinary_hospital, :string
    field :contract_bundling_code, :string
    field :usaspending_permalink, :string
    field :parent_award_modification_number, :string
    field :award_type, :string
    field :research_code, :string
    field :parent_award_type_code, :string
    field :minority_owned_business, :string
    field :recipient_country_name, :string
    field :product_or_service_code, :string
    field :primary_place_of_performance_city_name, :string
    field :native_hawaiian_servicing_institution, :string
    field :sea_transportation_code, :string
    field :corporate_entity_not_tax_exempt, :string
    field :type_of_idc, :string
    field :domestic_or_foreign_entity, :string
    field :prime_award_base_transaction_description, :string
    field :contingency_humanitarian_or_peacekeeping_operation_code, :string
    field :small_disadvantaged_business, :string
    field :federal_accounts_funding_this_award, :string
    field :potential_total_value_of_award, :string
    field :tribally_owned_firm, :string
    field :recipient_address_line_1, :string
    field :other_not_for_profit_organization, :string
    field :sea_transportation, :string
    field :recipient_parent_name, :string
    field :sam_exception, :string
    field :other_statutory_authority, :string
    field :primary_place_of_performance_county_name, :string
    field :type_of_contract_pricing, :string
    field :educational_institution, :string
    field :contract_award_unique_key, :string
    field :contingency_humanitarian_or_peacekeeping_operation, :string
    field :women_owned_small_business, :string
    field :subcontracting_plan_code, :string
    field :small_business_competitiveness_demonstration_program, :string
    field :prime_award_transaction_place_of_performance_state_fips_code, :string
    field :multiple_or_single_award_idv_code, :string
    field :recipient_county_name, :string
    field :action_type, :string
    field :highly_compensated_officer_2_name, :string
    field :total_outlayed_amount_for_overall_award, :string
    field :evaluated_preference_code, :string
    field :highly_compensated_officer_5_name, :string
    field :hispanic_servicing_institution, :string
    field :clinger_cohen_act_planning, :string
    field :multiple_or_single_award_idv, :string
    field :dod_claimant_program_code, :string
    field :emerging_small_business, :string
    field :domestic_shelter, :string
    field :contracting_officers_determination_of_business_size_code, :string
    field :manufacturer_of_goods, :string
    field :cost_accounting_standards_clause_code, :string
    field :port_authority, :string
    field :purchase_card_as_payment_method, :string
    field :disaster_emergency_fund_codes_for_overall_award, :string
    field :action_date_fiscal_year, :string
    field :federal_agency, :string
    field :dod_acquisition_program_code, :string
    field :community_development_corporation, :string
    field :asian_pacific_american_owned_business, :string
    field :national_interest_action, :string
    field :primary_place_of_performance_country_code, :string
    field :contract_financing, :string
    field :performance_based_service_acquisition, :string
    field :federally_funded_research_and_development_corp, :string
    field :receives_contracts, :string
    field :recipient_city_name, :string
    field :place_of_manufacture, :string
    field :fed_biz_opps, :string
    field :performance_based_service_acquisition_code, :string
    field :undefinitized_action, :string
    field :local_area_set_aside, :string
    field :fair_opportunity_limited_sources, :string
    field :highly_compensated_officer_1_amount, :string
    field :recovered_materials_sustainability_code, :string
    field :foundation, :string
    field :base_and_exercised_options_value, :string
    field :highly_compensated_officer_4_amount, :string
    field :cost_or_pricing_data, :string
    field :labor_standards, :string
    field :funding_office_code, :string
    field :recipient_fax_number, :string
    field :type_of_idc_code, :string
    field :subcontracting_plan, :string
    field :county_local_government, :string
    field :tribal_college, :string
    field :school_of_forestry, :string
    field :foreign_funding_description, :string
    field :township_local_government, :string
    field :object_classes_funding_this_award, :string
    field :contract_financing_code, :string
    field :recipient_address_line_2, :string
    field :foreign_funding, :string
    field :economically_disadvantaged_women_owned_small_business, :string
    field :primary_place_of_performance_state_code, :string
    field :cost_accounting_standards_clause, :string
    field :funding_sub_agency_code, :string
    field :sole_proprietorship, :string
    field :other_than_full_and_open_competition_code, :string
    field :epa_designated_product_code, :string
    field :inter_municipal_local_government, :string
    field :clinger_cohen_act_planning_code, :string
    field :base_and_all_options_value, :string
    field :organizational_type, :string
    field :solicitation_date, :string
    field :funding_sub_agency_name, :string
    field :current_total_value_of_award, :string
    field :materials_supplies_articles_equipment_code, :string
    field :construction_wage_rate_requirements_code, :string
    field :information_technology_commercial_item_category_code, :string
    field :undefinitized_action_code, :string
    field :limited_liability_corporation, :string
    field :minority_institution, :string
    field :highly_compensated_officer_5_amount, :string
    field :self_certified_small_disadvantaged_business, :string
    field :parent_award_agency_name, :string
    field :hospital_flag, :string
    field :parent_award_id_piid, :string
    field :initial_report_date, :string
    field :us_government_entity, :string
    field :dod_acquisition_program_description, :string
    field :joint_venture_women_owned_small_business, :string
    field :contracting_officers_determination_of_business_size, :string
    field :interagency_contracting_authority_code, :string
    field :awarding_office_code, :string
    field :program_acronym, :string
    field :woman_owned_business, :string
    field :consolidated_contract_code, :string
    field :national_interest_action_code, :string
    field :housing_authorities_public_tribal, :string
    field :prime_award_transaction_place_of_performance_county_fips_code, :string
    field :prime_award_transaction_recipient_state_fips_code, :string
    field :other_minority_owned_business, :string
    field :funding_agency_name, :string
    field :total_dollars_obligated, :string
    field :the_ability_one_program, :string
    field :outlayed_amount_from_IIJA_supplemental_for_overall_award, :string
    field :government_furnished_property_code, :string
    field :type_of_contract_pricing_code, :string
    field :primary_place_of_performance_country_name, :string
    field :domestic_or_foreign_entity_code, :string
    field :purchase_card_as_payment_method_code, :string
    field :highly_compensated_officer_1_name, :string
    field :awarding_sub_agency_code, :string
    field :idv_type, :string
    field :extent_competed, :string
    field :cage_code, :string
    field :period_of_performance_potential_end_date, :string
    field :alaskan_native_servicing_institution, :string
    field :obligated_amount_from_IIJA_supplemental_for_overall_award, :string
    field :local_government_owned, :string
    field :product_or_service_code_description, :string
    field :private_university_or_college, :string
    field :fed_biz_opps_code, :string
    field :primary_place_of_performance_state_name, :string
    field :consolidated_contract, :string
    field :us_federal_government, :string
    field :awarding_sub_agency_name, :string
    field :multi_year_contract, :string
    field :recipient_state_code, :string
    field :period_of_performance_start_date, :string
    field :recipient_zip_4_code, :string
    field :place_of_manufacture_code, :string
    field :materials_supplies_articles_equipment, :string
    field :veterinary_college, :string
    field :government_furnished_property, :string
    field :american_indian_owned_business, :string
    field :type_of_set_aside, :string
    field :council_of_governments, :string
    field :us_state_government, :string
    field :indian_tribe_federally_recognized, :string
    field :recipient_name, :string
    field :foreign_government, :string
    field :awarding_agency_code, :string
    field :recipient_phone_number, :string
    field :program_activities_funding_this_award, :string
    field :epa_designated_product, :string
    field :funding_office_name, :string
    field :price_evaluation_adjustment_preference_percent_difference, :string
    field :action_type_code, :string

  end

  @doc false
  def changeset(contract_award, attrs) do
    contract_award
    |> cast(attrs, [:contract_transaction_unique_key, :contract_award_unique_key, :award_id_piid, :modification_number, :transaction_number, :parent_award_agency_id, :parent_award_agency_name, :parent_award_id_piid, :parent_award_modification_number, :federal_action_obligation, :total_dollars_obligated, :total_outlayed_amount_for_overall_award, :base_and_exercised_options_value, :current_total_value_of_award, :base_and_all_options_value, :potential_total_value_of_award, :disaster_emergency_fund_codes_for_overall_award, :"outlayed_amount_from_COVID-19_supplementals_for_overall_award", :"obligated_amount_from_COVID-19_supplementals_for_overall_award", :outlayed_amount_from_IIJA_supplemental_for_overall_award, :obligated_amount_from_IIJA_supplemental_for_overall_award, :action_date, :action_date_fiscal_year, :period_of_performance_start_date, :period_of_performance_current_end_date, :period_of_performance_potential_end_date, :ordering_period_end_date, :solicitation_date, :awarding_agency_code, :awarding_agency_name, :awarding_sub_agency_code, :awarding_sub_agency_name, :awarding_office_code, :awarding_office_name, :funding_agency_code, :funding_agency_name, :funding_sub_agency_code, :funding_sub_agency_name, :funding_office_code, :funding_office_name, :treasury_accounts_funding_this_award, :federal_accounts_funding_this_award, :object_classes_funding_this_award, :program_activities_funding_this_award, :foreign_funding, :foreign_funding_description, :sam_exception, :sam_exception_description, :recipient_uei, :recipient_duns, :recipient_name, :recipient_name_raw, :recipient_doing_business_as_name, :cage_code, :recipient_parent_uei, :recipient_parent_duns, :recipient_parent_name, :recipient_parent_name_raw, :recipient_country_code, :recipient_country_name, :recipient_address_line_1, :recipient_address_line_2, :recipient_city_name, :prime_award_transaction_recipient_county_fips_code, :recipient_county_name, :prime_award_transaction_recipient_state_fips_code, :recipient_state_code, :recipient_state_name, :recipient_zip_4_code, :prime_award_transaction_recipient_cd_original, :prime_award_transaction_recipient_cd_current, :recipient_phone_number, :recipient_fax_number, :primary_place_of_performance_country_code, :primary_place_of_performance_country_name, :primary_place_of_performance_city_name, :prime_award_transaction_place_of_performance_county_fips_code, :primary_place_of_performance_county_name, :prime_award_transaction_place_of_performance_state_fips_code, :primary_place_of_performance_state_code, :primary_place_of_performance_state_name, :primary_place_of_performance_zip_4, :prime_award_transaction_place_of_performance_cd_original, :prime_award_transaction_place_of_performance_cd_current, :award_or_idv_flag, :award_type_code, :award_type, :idv_type_code, :idv_type, :multiple_or_single_award_idv_code, :multiple_or_single_award_idv, :type_of_idc_code, :type_of_idc, :type_of_contract_pricing_code, :type_of_contract_pricing, :transaction_description, :prime_award_base_transaction_description, :action_type_code, :action_type, :solicitation_identifier, :number_of_actions, :inherently_governmental_functions, :inherently_governmental_functions_description, :product_or_service_code, :product_or_service_code_description, :contract_bundling_code, :contract_bundling, :dod_claimant_program_code, :dod_claimant_program_description, :naics_code, :naics_description, :recovered_materials_sustainability_code, :recovered_materials_sustainability, :domestic_or_foreign_entity_code, :domestic_or_foreign_entity, :dod_acquisition_program_code, :dod_acquisition_program_description, :information_technology_commercial_item_category_code, :information_technology_commercial_item_category, :epa_designated_product_code, :epa_designated_product, :country_of_product_or_service_origin_code, :country_of_product_or_service_origin, :place_of_manufacture_code, :place_of_manufacture, :subcontracting_plan_code, :subcontracting_plan, :extent_competed_code, :extent_competed, :solicitation_procedures_code, :solicitation_procedures, :type_of_set_aside_code, :type_of_set_aside, :evaluated_preference_code, :evaluated_preference, :research_code, :research, :fair_opportunity_limited_sources_code, :fair_opportunity_limited_sources, :other_than_full_and_open_competition_code, :other_than_full_and_open_competition, :number_of_offers_received, :commercial_item_acquisition_procedures_code, :commercial_item_acquisition_procedures, :small_business_competitiveness_demonstration_program, :simplified_procedures_for_certain_commercial_items_code, :simplified_procedures_for_certain_commercial_items, :a76_fair_act_action_code, :a76_fair_act_action, :fed_biz_opps_code, :fed_biz_opps, :local_area_set_aside_code, :local_area_set_aside, :price_evaluation_adjustment_preference_percent_difference, :clinger_cohen_act_planning_code, :clinger_cohen_act_planning, :materials_supplies_articles_equipment_code, :materials_supplies_articles_equipment, :labor_standards_code, :labor_standards, :construction_wage_rate_requirements_code, :construction_wage_rate_requirements, :interagency_contracting_authority_code, :interagency_contracting_authority, :other_statutory_authority, :program_acronym, :parent_award_type_code, :parent_award_type, :parent_award_single_or_multiple_code, :parent_award_single_or_multiple, :major_program, :national_interest_action_code, :national_interest_action, :cost_or_pricing_data_code, :cost_or_pricing_data, :cost_accounting_standards_clause_code, :cost_accounting_standards_clause, :government_furnished_property_code, :government_furnished_property, :sea_transportation_code, :sea_transportation, :undefinitized_action_code, :undefinitized_action, :consolidated_contract_code, :consolidated_contract, :performance_based_service_acquisition_code, :performance_based_service_acquisition, :multi_year_contract_code, :multi_year_contract, :contract_financing_code, :contract_financing, :purchase_card_as_payment_method_code, :purchase_card_as_payment_method, :contingency_humanitarian_or_peacekeeping_operation_code, :contingency_humanitarian_or_peacekeeping_operation, :alaskan_native_corporation_owned_firm, :american_indian_owned_business, :indian_tribe_federally_recognized, :native_hawaiian_organization_owned_firm, :tribally_owned_firm, :veteran_owned_business, :service_disabled_veteran_owned_business, :woman_owned_business, :women_owned_small_business, :economically_disadvantaged_women_owned_small_business, :joint_venture_women_owned_small_business, :joint_venture_economic_disadvantaged_women_owned_small_bus, :minority_owned_business, :subcontinent_asian_asian_indian_american_owned_business, :asian_pacific_american_owned_business, :black_american_owned_business, :hispanic_american_owned_business, :native_american_owned_business, :other_minority_owned_business, :contracting_officers_determination_of_business_size, :contracting_officers_determination_of_business_size_code, :emerging_small_business, :community_developed_corporation_owned_firm, :labor_surplus_area_firm, :us_federal_government, :federally_funded_research_and_development_corp, :federal_agency, :us_state_government, :us_local_government, :city_local_government, :county_local_government, :inter_municipal_local_government, :local_government_owned, :municipality_local_government, :school_district_local_government, :township_local_government, :us_tribal_government, :foreign_government, :organizational_type, :corporate_entity_not_tax_exempt, :corporate_entity_tax_exempt, :partnership_or_limited_liability_partnership, :sole_proprietorship, :small_agricultural_cooperative, :international_organization, :us_government_entity, :community_development_corporation, :domestic_shelter, :educational_institution, :foundation, :hospital_flag, :manufacturer_of_goods, :veterinary_hospital, :hispanic_servicing_institution, :receives_contracts, :receives_financial_assistance, :receives_contracts_and_financial_assistance, :airport_authority, :council_of_governments, :housing_authorities_public_tribal, :interstate_entity, :planning_commission, :port_authority, :transit_authority, :subchapter_scorporation, :limited_liability_corporation, :foreign_owned, :for_profit_organization, :nonprofit_organization, :other_not_for_profit_organization, :the_ability_one_program, :private_university_or_college, :state_controlled_institution_of_higher_learning, :land_grant_college, :minority_institution, :historically_black_college, :tribal_college, :alaskan_native_servicing_institution, :native_hawaiian_servicing_institution, :school_of_forestry, :veterinary_college, :dot_certified_disadvantage, :self_certified_small_disadvantaged_business, :small_disadvantaged_business, :c8a_program_participant, :historically_underutilized_business_zone_hubzone_firm, :sba_certified_8a_joint_venture, :highly_compensated_officer_1_name, :highly_compensated_officer_1_amount, :highly_compensated_officer_2_name, :highly_compensated_officer_2_amount, :highly_compensated_officer_3_name, :highly_compensated_officer_3_amount, :highly_compensated_officer_4_name, :highly_compensated_officer_4_amount, :highly_compensated_officer_5_name, :highly_compensated_officer_5_amount, :usaspending_permalink, :initial_report_date, :last_modified_date])
    |> validate_required([:contract_transaction_unique_key, :contract_award_unique_key, :award_id_piid, :modification_number, :transaction_number, :parent_award_agency_id, :parent_award_agency_name, :parent_award_id_piid, :parent_award_modification_number, :federal_action_obligation, :total_dollars_obligated, :total_outlayed_amount_for_overall_award, :base_and_exercised_options_value, :current_total_value_of_award, :base_and_all_options_value, :potential_total_value_of_award, :disaster_emergency_fund_codes_for_overall_award, :"outlayed_amount_from_COVID-19_supplementals_for_overall_award", :"obligated_amount_from_COVID-19_supplementals_for_overall_award", :outlayed_amount_from_IIJA_supplemental_for_overall_award, :obligated_amount_from_IIJA_supplemental_for_overall_award, :action_date, :action_date_fiscal_year, :period_of_performance_start_date, :period_of_performance_current_end_date, :period_of_performance_potential_end_date, :ordering_period_end_date, :solicitation_date, :awarding_agency_code, :awarding_agency_name, :awarding_sub_agency_code, :awarding_sub_agency_name, :awarding_office_code, :awarding_office_name, :funding_agency_code, :funding_agency_name, :funding_sub_agency_code, :funding_sub_agency_name, :funding_office_code, :funding_office_name, :treasury_accounts_funding_this_award, :federal_accounts_funding_this_award, :object_classes_funding_this_award, :program_activities_funding_this_award, :foreign_funding, :foreign_funding_description, :sam_exception, :sam_exception_description, :recipient_uei, :recipient_duns, :recipient_name, :recipient_name_raw, :recipient_doing_business_as_name, :cage_code, :recipient_parent_uei, :recipient_parent_duns, :recipient_parent_name, :recipient_parent_name_raw, :recipient_country_code, :recipient_country_name, :recipient_address_line_1, :recipient_address_line_2, :recipient_city_name, :prime_award_transaction_recipient_county_fips_code, :recipient_county_name, :prime_award_transaction_recipient_state_fips_code, :recipient_state_code, :recipient_state_name, :recipient_zip_4_code, :prime_award_transaction_recipient_cd_original, :prime_award_transaction_recipient_cd_current, :recipient_phone_number, :recipient_fax_number, :primary_place_of_performance_country_code, :primary_place_of_performance_country_name, :primary_place_of_performance_city_name, :prime_award_transaction_place_of_performance_county_fips_code, :primary_place_of_performance_county_name, :prime_award_transaction_place_of_performance_state_fips_code, :primary_place_of_performance_state_code, :primary_place_of_performance_state_name, :primary_place_of_performance_zip_4, :prime_award_transaction_place_of_performance_cd_original, :prime_award_transaction_place_of_performance_cd_current, :award_or_idv_flag, :award_type_code, :award_type, :idv_type_code, :idv_type, :multiple_or_single_award_idv_code, :multiple_or_single_award_idv, :type_of_idc_code, :type_of_idc, :type_of_contract_pricing_code, :type_of_contract_pricing, :transaction_description, :prime_award_base_transaction_description, :action_type_code, :action_type, :solicitation_identifier, :number_of_actions, :inherently_governmental_functions, :inherently_governmental_functions_description, :product_or_service_code, :product_or_service_code_description, :contract_bundling_code, :contract_bundling, :dod_claimant_program_code, :dod_claimant_program_description, :naics_code, :naics_description, :recovered_materials_sustainability_code, :recovered_materials_sustainability, :domestic_or_foreign_entity_code, :domestic_or_foreign_entity, :dod_acquisition_program_code, :dod_acquisition_program_description, :information_technology_commercial_item_category_code, :information_technology_commercial_item_category, :epa_designated_product_code, :epa_designated_product, :country_of_product_or_service_origin_code, :country_of_product_or_service_origin, :place_of_manufacture_code, :place_of_manufacture, :subcontracting_plan_code, :subcontracting_plan, :extent_competed_code, :extent_competed, :solicitation_procedures_code, :solicitation_procedures, :type_of_set_aside_code, :type_of_set_aside, :evaluated_preference_code, :evaluated_preference, :research_code, :research, :fair_opportunity_limited_sources_code, :fair_opportunity_limited_sources, :other_than_full_and_open_competition_code, :other_than_full_and_open_competition, :number_of_offers_received, :commercial_item_acquisition_procedures_code, :commercial_item_acquisition_procedures, :small_business_competitiveness_demonstration_program, :simplified_procedures_for_certain_commercial_items_code, :simplified_procedures_for_certain_commercial_items, :a76_fair_act_action_code, :a76_fair_act_action, :fed_biz_opps_code, :fed_biz_opps, :local_area_set_aside_code, :local_area_set_aside, :price_evaluation_adjustment_preference_percent_difference, :clinger_cohen_act_planning_code, :clinger_cohen_act_planning, :materials_supplies_articles_equipment_code, :materials_supplies_articles_equipment, :labor_standards_code, :labor_standards, :construction_wage_rate_requirements_code, :construction_wage_rate_requirements, :interagency_contracting_authority_code, :interagency_contracting_authority, :other_statutory_authority, :program_acronym, :parent_award_type_code, :parent_award_type, :parent_award_single_or_multiple_code, :parent_award_single_or_multiple, :major_program, :national_interest_action_code, :national_interest_action, :cost_or_pricing_data_code, :cost_or_pricing_data, :cost_accounting_standards_clause_code, :cost_accounting_standards_clause, :government_furnished_property_code, :government_furnished_property, :sea_transportation_code, :sea_transportation, :undefinitized_action_code, :undefinitized_action, :consolidated_contract_code, :consolidated_contract, :performance_based_service_acquisition_code, :performance_based_service_acquisition, :multi_year_contract_code, :multi_year_contract, :contract_financing_code, :contract_financing, :purchase_card_as_payment_method_code, :purchase_card_as_payment_method, :contingency_humanitarian_or_peacekeeping_operation_code, :contingency_humanitarian_or_peacekeeping_operation, :alaskan_native_corporation_owned_firm, :american_indian_owned_business, :indian_tribe_federally_recognized, :native_hawaiian_organization_owned_firm, :tribally_owned_firm, :veteran_owned_business, :service_disabled_veteran_owned_business, :woman_owned_business, :women_owned_small_business, :economically_disadvantaged_women_owned_small_business, :joint_venture_women_owned_small_business, :joint_venture_economic_disadvantaged_women_owned_small_bus, :minority_owned_business, :subcontinent_asian_asian_indian_american_owned_business, :asian_pacific_american_owned_business, :black_american_owned_business, :hispanic_american_owned_business, :native_american_owned_business, :other_minority_owned_business, :contracting_officers_determination_of_business_size, :contracting_officers_determination_of_business_size_code, :emerging_small_business, :community_developed_corporation_owned_firm, :labor_surplus_area_firm, :us_federal_government, :federally_funded_research_and_development_corp, :federal_agency, :us_state_government, :us_local_government, :city_local_government, :county_local_government, :inter_municipal_local_government, :local_government_owned, :municipality_local_government, :school_district_local_government, :township_local_government, :us_tribal_government, :foreign_government, :organizational_type, :corporate_entity_not_tax_exempt, :corporate_entity_tax_exempt, :partnership_or_limited_liability_partnership, :sole_proprietorship, :small_agricultural_cooperative, :international_organization, :us_government_entity, :community_development_corporation, :domestic_shelter, :educational_institution, :foundation, :hospital_flag, :manufacturer_of_goods, :veterinary_hospital, :hispanic_servicing_institution, :receives_contracts, :receives_financial_assistance, :receives_contracts_and_financial_assistance, :airport_authority, :council_of_governments, :housing_authorities_public_tribal, :interstate_entity, :planning_commission, :port_authority, :transit_authority, :subchapter_scorporation, :limited_liability_corporation, :foreign_owned, :for_profit_organization, :nonprofit_organization, :other_not_for_profit_organization, :the_ability_one_program, :private_university_or_college, :state_controlled_institution_of_higher_learning, :land_grant_college, :minority_institution, :historically_black_college, :tribal_college, :alaskan_native_servicing_institution, :native_hawaiian_servicing_institution, :school_of_forestry, :veterinary_college, :dot_certified_disadvantage, :self_certified_small_disadvantaged_business, :small_disadvantaged_business, :c8a_program_participant, :historically_underutilized_business_zone_hubzone_firm, :sba_certified_8a_joint_venture, :highly_compensated_officer_1_name, :highly_compensated_officer_1_amount, :highly_compensated_officer_2_name, :highly_compensated_officer_2_amount, :highly_compensated_officer_3_name, :highly_compensated_officer_3_amount, :highly_compensated_officer_4_name, :highly_compensated_officer_4_amount, :highly_compensated_officer_5_name, :highly_compensated_officer_5_amount, :usaspending_permalink, :initial_report_date, :last_modified_date])
  end
end
