defmodule GovBidify.Repo.Migrations.CreateContractAwards do
  use Ecto.Migration

  def change do
    create table(:contract_awards) do
      add :contract_transaction_unique_key, :string
      add :contract_award_unique_key, :string
      add :award_id_piid, :string
      add :modification_number, :string
      add :transaction_number, :string
      add :parent_award_agency_id, :string
      add :parent_award_agency_name, :string
      add :parent_award_id_piid, :string
      add :parent_award_modification_number, :string
      add :federal_action_obligation, :string
      add :total_dollars_obligated, :string
      add :total_outlayed_amount_for_overall_award, :string
      add :base_and_exercised_options_value, :string
      add :current_total_value_of_award, :string
      add :base_and_all_options_value, :string
      add :potential_total_value_of_award, :string
      add :disaster_emergency_fund_codes_for_overall_award, :text
      add :"outlayed_amount_from_COVID-19_supplementals_for_overall_award", :string
      add :"obligated_amount_from_COVID-19_supplementals_for_overall_award", :string
      add :outlayed_amount_from_IIJA_supplemental_for_overall_award, :string
      add :obligated_amount_from_IIJA_supplemental_for_overall_award, :string
      add :action_date, :string
      add :action_date_fiscal_year, :string
      add :period_of_performance_start_date, :string
      add :period_of_performance_current_end_date, :string
      add :period_of_performance_potential_end_date, :string
      add :ordering_period_end_date, :string
      add :solicitation_date, :string
      add :awarding_agency_code, :string
      add :awarding_agency_name, :string
      add :awarding_sub_agency_code, :string
      add :awarding_sub_agency_name, :string
      add :awarding_office_code, :string
      add :awarding_office_name, :string
      add :funding_agency_code, :string
      add :funding_agency_name, :string
      add :funding_sub_agency_code, :string
      add :funding_sub_agency_name, :string
      add :funding_office_code, :string
      add :funding_office_name, :string
      add :treasury_accounts_funding_this_award, :text
      add :federal_accounts_funding_this_award, :text
      add :object_classes_funding_this_award, :text
      add :program_activities_funding_this_award, :text
      add :foreign_funding, :string
      add :foreign_funding_description, :string
      add :sam_exception, :string
      add :sam_exception_description, :string
      add :recipient_uei, :string
      add :recipient_duns, :string
      add :recipient_name, :string
      add :recipient_name_raw, :string
      add :recipient_doing_business_as_name, :string
      add :cage_code, :string
      add :recipient_parent_uei, :string
      add :recipient_parent_duns, :string
      add :recipient_parent_name, :string
      add :recipient_parent_name_raw, :string
      add :recipient_country_code, :string
      add :recipient_country_name, :string
      add :recipient_address_line_1, :string
      add :recipient_address_line_2, :string
      add :recipient_city_name, :string
      add :prime_award_transaction_recipient_county_fips_code, :string
      add :recipient_county_name, :string
      add :prime_award_transaction_recipient_state_fips_code, :string
      add :recipient_state_code, :string
      add :recipient_state_name, :string
      add :recipient_zip_4_code, :string
      add :prime_award_transaction_recipient_cd_original, :string
      add :prime_award_transaction_recipient_cd_current, :string
      add :recipient_phone_number, :string
      add :recipient_fax_number, :string
      add :primary_place_of_performance_country_code, :string
      add :primary_place_of_performance_country_name, :string
      add :primary_place_of_performance_city_name, :string
      add :prime_award_transaction_place_of_performance_county_fips_code, :string
      add :primary_place_of_performance_county_name, :string
      add :prime_award_transaction_place_of_performance_state_fips_code, :string
      add :primary_place_of_performance_state_code, :string
      add :primary_place_of_performance_state_name, :string
      add :primary_place_of_performance_zip_4, :string
      add :prime_award_transaction_place_of_performance_cd_original, :string
      add :prime_award_transaction_place_of_performance_cd_current, :string
      add :award_or_idv_flag, :string
      add :award_type_code, :string
      add :award_type, :string
      add :idv_type_code, :string
      add :idv_type, :string
      add :multiple_or_single_award_idv_code, :string
      add :multiple_or_single_award_idv, :string
      add :type_of_idc_code, :string
      add :type_of_idc, :string
      add :type_of_contract_pricing_code, :string
      add :type_of_contract_pricing, :string
      add :transaction_description, :text
      add :prime_award_base_transaction_description, :text
      add :action_type_code, :string
      add :action_type, :string
      add :solicitation_identifier, :string
      add :number_of_actions, :string
      add :inherently_governmental_functions, :string
      add :inherently_governmental_functions_description, :string
      add :product_or_service_code, :string
      add :product_or_service_code_description, :string
      add :contract_bundling_code, :string
      add :contract_bundling, :string
      add :dod_claimant_program_code, :string
      add :dod_claimant_program_description, :string
      add :naics_code, :string
      add :naics_description, :string
      add :recovered_materials_sustainability_code, :string
      add :recovered_materials_sustainability, :string
      add :domestic_or_foreign_entity_code, :string
      add :domestic_or_foreign_entity, :string
      add :dod_acquisition_program_code, :string
      add :dod_acquisition_program_description, :string
      add :information_technology_commercial_item_category_code, :string
      add :information_technology_commercial_item_category, :string
      add :epa_designated_product_code, :string
      add :epa_designated_product, :string
      add :country_of_product_or_service_origin_code, :string
      add :country_of_product_or_service_origin, :string
      add :place_of_manufacture_code, :string
      add :place_of_manufacture, :string
      add :subcontracting_plan_code, :string
      add :subcontracting_plan, :string
      add :extent_competed_code, :string
      add :extent_competed, :string
      add :solicitation_procedures_code, :string
      add :solicitation_procedures, :string
      add :type_of_set_aside_code, :string
      add :type_of_set_aside, :string
      add :evaluated_preference_code, :string
      add :evaluated_preference, :string
      add :research_code, :string
      add :research, :string
      add :fair_opportunity_limited_sources_code, :string
      add :fair_opportunity_limited_sources, :string
      add :other_than_full_and_open_competition_code, :string
      add :other_than_full_and_open_competition, :string
      add :number_of_offers_received, :string
      add :commercial_item_acquisition_procedures_code, :string
      add :commercial_item_acquisition_procedures, :string
      add :small_business_competitiveness_demonstration_program, :string
      add :simplified_procedures_for_certain_commercial_items_code, :string
      add :simplified_procedures_for_certain_commercial_items, :string
      add :a76_fair_act_action_code, :string
      add :a76_fair_act_action, :string
      add :fed_biz_opps_code, :string
      add :fed_biz_opps, :string
      add :local_area_set_aside_code, :string
      add :local_area_set_aside, :string
      add :price_evaluation_adjustment_preference_percent_difference, :string
      add :clinger_cohen_act_planning_code, :string
      add :clinger_cohen_act_planning, :string
      add :materials_supplies_articles_equipment_code, :string
      add :materials_supplies_articles_equipment, :string
      add :labor_standards_code, :string
      add :labor_standards, :string
      add :construction_wage_rate_requirements_code, :string
      add :construction_wage_rate_requirements, :string
      add :interagency_contracting_authority_code, :string
      add :interagency_contracting_authority, :string
      add :other_statutory_authority, :string
      add :program_acronym, :string
      add :parent_award_type_code, :string
      add :parent_award_type, :string
      add :parent_award_single_or_multiple_code, :string
      add :parent_award_single_or_multiple, :string
      add :major_program, :string
      add :national_interest_action_code, :string
      add :national_interest_action, :string
      add :cost_or_pricing_data_code, :string
      add :cost_or_pricing_data, :string
      add :cost_accounting_standards_clause_code, :string
      add :cost_accounting_standards_clause, :string
      add :government_furnished_property_code, :string
      add :government_furnished_property, :string
      add :sea_transportation_code, :string
      add :sea_transportation, :string
      add :undefinitized_action_code, :string
      add :undefinitized_action, :string
      add :consolidated_contract_code, :string
      add :consolidated_contract, :string
      add :performance_based_service_acquisition_code, :string
      add :performance_based_service_acquisition, :string
      add :multi_year_contract_code, :string
      add :multi_year_contract, :string
      add :contract_financing_code, :string
      add :contract_financing, :string
      add :purchase_card_as_payment_method_code, :string
      add :purchase_card_as_payment_method, :string
      add :contingency_humanitarian_or_peacekeeping_operation_code, :string
      add :contingency_humanitarian_or_peacekeeping_operation, :string
      add :alaskan_native_corporation_owned_firm, :string
      add :american_indian_owned_business, :string
      add :indian_tribe_federally_recognized, :string
      add :native_hawaiian_organization_owned_firm, :string
      add :tribally_owned_firm, :string
      add :veteran_owned_business, :string
      add :service_disabled_veteran_owned_business, :string
      add :woman_owned_business, :string
      add :women_owned_small_business, :string
      add :economically_disadvantaged_women_owned_small_business, :string
      add :joint_venture_women_owned_small_business, :string
      add :joint_venture_economic_disadvantaged_women_owned_small_bus, :string
      add :minority_owned_business, :string
      add :subcontinent_asian_asian_indian_american_owned_business, :string
      add :asian_pacific_american_owned_business, :string
      add :black_american_owned_business, :string
      add :hispanic_american_owned_business, :string
      add :native_american_owned_business, :string
      add :other_minority_owned_business, :string
      add :contracting_officers_determination_of_business_size, :string
      add :contracting_officers_determination_of_business_size_code, :string
      add :emerging_small_business, :string
      add :community_developed_corporation_owned_firm, :string
      add :labor_surplus_area_firm, :string
      add :us_federal_government, :string
      add :federally_funded_research_and_development_corp, :string
      add :federal_agency, :string
      add :us_state_government, :string
      add :us_local_government, :string
      add :city_local_government, :string
      add :county_local_government, :string
      add :inter_municipal_local_government, :string
      add :local_government_owned, :string
      add :municipality_local_government, :string
      add :school_district_local_government, :string
      add :township_local_government, :string
      add :us_tribal_government, :string
      add :foreign_government, :string
      add :organizational_type, :string
      add :corporate_entity_not_tax_exempt, :string
      add :corporate_entity_tax_exempt, :string
      add :partnership_or_limited_liability_partnership, :string
      add :sole_proprietorship, :string
      add :small_agricultural_cooperative, :string
      add :international_organization, :string
      add :us_government_entity, :string
      add :community_development_corporation, :string
      add :domestic_shelter, :string
      add :educational_institution, :string
      add :foundation, :string
      add :hospital_flag, :string
      add :manufacturer_of_goods, :string
      add :veterinary_hospital, :string
      add :hispanic_servicing_institution, :string
      add :receives_contracts, :string
      add :receives_financial_assistance, :string
      add :receives_contracts_and_financial_assistance, :string
      add :airport_authority, :string
      add :council_of_governments, :string
      add :housing_authorities_public_tribal, :string
      add :interstate_entity, :string
      add :planning_commission, :string
      add :port_authority, :string
      add :transit_authority, :string
      add :subchapter_scorporation, :string
      add :limited_liability_corporation, :string
      add :foreign_owned, :string
      add :for_profit_organization, :string
      add :nonprofit_organization, :string
      add :other_not_for_profit_organization, :string
      add :the_ability_one_program, :string
      add :private_university_or_college, :string
      add :state_controlled_institution_of_higher_learning, :string
      add :land_grant_college, :string
      add :minority_institution, :string
      add :historically_black_college, :string
      add :tribal_college, :string
      add :alaskan_native_servicing_institution, :string
      add :native_hawaiian_servicing_institution, :string
      add :school_of_forestry, :string
      add :veterinary_college, :string
      add :dot_certified_disadvantage, :string
      add :self_certified_small_disadvantaged_business, :string
      add :small_disadvantaged_business, :string
      add :c8a_program_participant, :string
      add :historically_underutilized_business_zone_hubzone_firm, :string
      add :sba_certified_8a_joint_venture, :string
      add :highly_compensated_officer_1_name, :string
      add :highly_compensated_officer_1_amount, :string
      add :highly_compensated_officer_2_name, :string
      add :highly_compensated_officer_2_amount, :string
      add :highly_compensated_officer_3_name, :string
      add :highly_compensated_officer_3_amount, :string
      add :highly_compensated_officer_4_name, :string
      add :highly_compensated_officer_4_amount, :string
      add :highly_compensated_officer_5_name, :string
      add :highly_compensated_officer_5_amount, :string
      add :usaspending_permalink, :string
      add :initial_report_date, :string
      add :last_modified_date, :string

    end
  end
end
