defmodule GovBidify.Repo.Migrations.CreateEntities do
  use Ecto.Migration

  def change do
    create table(:entities) do
      add :unique_entity_id, :string
      add :blank_deprecated, :string
      add :entity_eft_indicator, :string
      add :cage_code, :string
      add :dodaac, :string
      add :sam_extract_code, :string
      add :purpose_of_registration, :string
      add :initial_registration_date, :date
      add :registration_expiration_date, :date
      add :last_update_date, :date
      add :activation_date, :date
      add :legal_business_name, :string
      add :dba_name, :string
      add :entity_division_name, :string
      add :entity_division_number, :string
      add :physical_address_line_1, :string
      add :physical_address_line_2, :string
      add :physical_address_city, :string
      add :physical_address_province_or_state, :string
      add :physical_address_zip_postal_code, :string
      add :physical_address_zip_code_4, :string
      add :physical_address_country_code, :string
      add :physical_address_congressional_district, :string
      add :d_b_open_data_flag, :string
      add :entity_start_date, :date
      add :fiscal_year_end_close_date, :date
      add :company_security_level, :string
      add :highest_employee_security_level, :string
      add :entity_url, :string
      add :entity_structure, :string
      add :state_of_incorporation, :string
      add :country_of_incorporation, :string
      add :business_type_counter, :string
      add :bus_type_string, :string
      add :agency_business_purpose, :string
      add :primary_naics, :string
      add :naics_code_counter, :string
      add :naics_code_string, :string
      add :psc_code_counter, :string
      add :psc_code_string, :string
      add :credit_card_usage, :string
      add :correspondence_flag, :string
      add :mailing_address_line_1, :string
      add :mailing_address_line_2, :string
      add :mailing_address_city, :string
      add :mailing_address_zip_postal_code, :string
      add :mailing_address_zip_code_4, :string
      add :mailing_address_country, :string
      add :mailing_address_state_or_province, :string
      add :govt_bus_poc_first_name, :string
      add :govt_bus_poc_middle_initial, :string
      add :govt_bus_poc_last_name, :string
      add :govt_bus_poc_title, :string
      add :govt_bus_poc_st_add_1, :string
      add :govt_bus_poc_st_add_2, :string
      add :govt_bus_poc_city, :string
      add :govt_bus_poc_zip_postal_code, :string
      add :govt_bus_poc_zip_code_4, :string
      add :govt_bus_poc_country_code, :string
      add :govt_bus_poc_state_or_province, :string
      add :govt_bus_poc_us_phone, :string
      add :govt_bus_poc_us_phone_ext, :string
      add :govt_bus_poc_non_us_phone, :string
      add :govt_bus_poc_fax_us_only, :string
      add :govt_bus_poc_email, :string
      add :alt_govt_bus_poc_first_name, :string
      add :alt_govt_bus_poc_middle_initial, :string
      add :alt_govt_bus_poc_last_name, :string
      add :alt_govt_bus_poc_title, :string
      add :alt_govt_bus_poc_st_add_1, :string
      add :alt_govt_bus_poc_st_add_2, :string
      add :alt_govt_bus_poc_city, :string
      add :alt_govt_bus_poc_zip_postal_code, :string
      add :alt_govt_bus_poc_zip_code_4, :string
      add :alt_govt_bus_poc_country_code, :string
      add :alt_govt_bus_poc_state_or_province, :string
      add :alt_govt_bus_poc_us_phone, :string
      add :alt_govt_bus_poc_us_phone_ext, :string
      add :alt_govt_bus_poc_non_us_phone, :string
      add :alt_govt_bus_poc_fax_us_only, :string
      add :alt_govt_bus_poc_email, :string
      add :past_perf_poc_poc_first_name, :string
      add :past_perf_poc_poc_middle_initial, :string
      add :past_perf_poc_poc_last_name, :string
      add :past_perf_poc_poc_title, :string
      add :past_perf_poc_st_add_1, :string
      add :past_perf_poc_st_add_2, :string
      add :past_perf_poc_city, :string
      add :past_perf_poc_zip_postal_code, :string
      add :past_perf_poc_zip_code_4, :string
      add :past_perf_poc_country_code, :string
      add :past_perf_poc_state_or_province, :string
      add :past_perf_poc_us_phone, :string
      add :past_perf_poc_us_phone_ext, :string
      add :past_perf_poc_non_us_phone, :string
      add :past_perf_poc_fax_us_only, :string
      add :past_perf_poc_email, :string
      add :alt_past_perf_poc_first_name, :string
      add :alt_past_perf_poc_middle_initial, :string
      add :alt_past_perf_poc_last_name, :string
      add :alt_past_perf_poc_title, :string
      add :alt_past_perf_poc_st_add_1, :string
      add :alt_past_perf_poc_st_add_2, :string
      add :alt_past_perf_poc_city, :string

      timestamps(type: :utc_datetime)
    end
  end
end
